version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.1-ce
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t appliedblockchain/libsnark-env .
      - run:
          name: Push Docker image
          command: docker push appliedblockchain/libsnark-env
 
